name: droidenv
channels:
  - rusty1s
  - pytorch
  - open3d-admin
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - pytorch-scatter
  - torchaudio
  - torchvision
  - open3d
  - pytorch=1.10.2=py3.9_cuda11.3_cudnn8.2.0_0
  - mkl=2024.0.0
  - cudatoolkit=11.3
  - tensorboard
  - scipy
  - opencv
  - tqdm
  - suitesparse
  - matplotlib
  - pyyaml
  - pyside2
  - setuptools=69.5.1



